### ISSUE TITLE
im having bad time with this error :(

### ISSUE THREAD

**Issue by Abdouflih** [pytube/pytube#1175]
**Im having bad time with this damn error:**
i made a pytube code and evertime i start it i get html.parser erreur
here is the code:
`from pytube import YouTube
url = input("enter your url: ")
my_video = YouTube(url)
yt = my_video.streams.get_highest_resolution()
print("downloading")
yt.download()
print("downloaded")
`
here is the erreur:
Traceback (most recent call last):
  File "c:/Users/106/Documents/Projects/gg.py", line 1, in <module>
    from pytube import YouTube
  File "C:\Python27\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Python27\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Python27\lib\site-packages\pytube\extract.py", line 8, in <module>
    from pytube.compat import urlencode
ImportError: cannot import name urlencode

anyone got a way to fix this?

**Comment by glubsy** [comment]
From the Readme.md: 

> Pytube requires an installation of python 3.6 or greater

Are you even using Python3? It seems you are using Python2 here.

**Comment by Abdouflih** [comment]
So Pytube Doesnt work in Python 2.7?

**Comment by glubsy** [comment]
No, it probably won't work as you have experienced yourself. Some standard librairies have changed a lot, and the syntax has changed as well. You could probably port pytube to 2.7 yourself if you are motivated enough.
